### ISSUE TITLE
KV whitespace trim should only do beginning/end of value

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-kv#10]
(This issue was originally filed by @markwalkom at https://github.com/elastic/logstash/issues/2459)

---

If I have a dataset like this;

``` csv
"sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom"
```

And this Logstash config, which removes quotes and also trims whitespace;

```
input {
  stdin {}
}

filter {
  kv {
    trim => "\"\ "
    trimkey => "\"\ \(\)"
    field_split => ","
    value_split => ":"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

The output I get is mashed together `sentence` and `author` values;

``` shell
 echo ""sentence": "the quick brown fox jumped over the duck", "author": "Mark Walkom""|bin/logstash agent -f conf/kvbug.conf
Using milestone 2 filter plugin 'kv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "sentence: the quick brown fox jumped over the duck, author: Mark Walkom",
      "@version" => "1",
    "@timestamp" => "2015-01-28T02:57:09.654Z",
          "host" => "bender.local",
      "sentence" => "thequickbrownfoxjumpedovertheduck",
        "author" => "MarkWalkom"
}
```

I realise that [the docs](http://logstash.net/docs/1.4.2/filters/kv#trim) explicitly say _"A string of characters to trim from the value"_ which implies it'll trim these chars from the entire string irrespective of location, but given `trim` in the other filters only does the start and beginning of a field, it'd be great if it did the same for the kv filter.

**Comment by tomkregenbild** [comment]
+1

**Comment by berglh** [comment]
I can see the need for both. Currently I need to do mutate gsubs to clean up the data before parsing it through the kv filter to get the required output. The ability to trim a regex character class from both ends of the key and value would remove the need for this extra filter. Maybe something like this:

`filter {
  kv {
          ...
          field_split => "\n"
          value_split => "="
          trimkey => " \t\""
          trimkey_end => "\ \:"
          trim => "\t\""
          trim_end => "\ "
  }
}`

**Comment by jethrovt** [comment]
+1

**Comment by anderius** [comment]
+1

**Comment by jsvd** [comment]
version 4.0.0 has been published and addresses this issue, for more information see #39
