### ISSUE TITLE
Keys with no values are used as field value

### ISSUE THREAD

**Issue by jjfalling** [logstash-plugins/logstash-filter-kv#22]
If a key in an event has no value then the Key and separator are added to the field as a value. For example the event `Status: ` will appear as `"Code" => "Status: "` instead of simply omitting the field. 

It looks like this issue appeared in https://github.com/logstash-plugins/logstash-filter-kv/commit/43ec4d568fb6f151ad8cabaf33de8630f8eddf78#diff-2953f0582e05707c33324c5c26363224L175 

@purbon

**Comment by untergeek** [comment]
Going to add a test to the suite to confirm this behavior, and validate the fix.

**Comment by toddiuszho** [comment]
Why is the desired behavior to omit the field instead of `"Status" => ""` ?
