### ISSUE TITLE
Add an option to lowercase all created fields

### ISSUE THREAD

**Issue by mut3** [logstash-plugins/logstash-filter-kv#24]
The idea is to add an option to make the key names lowercase before creating fields.

An example of when this would be useful is when using kv to parse URL parameters

```
....&foo=bar&ip=127.0.0.1
```

could be accepted by the web application the exact same way if it was

```
...&FoO=bar&IP=127.0.0.1
```

but kv would create 4 distinct fields.

Field values can be lowercased with mutate, but there is no way to lowercase field names generated during parsing without knowing what the will be beforehand.

**Comment by fbaligand** [comment]
@mut3

You can already do that using this option :
transform_key => "lowercase"

**Comment by mut3** [comment]
I couldn't at the time i made this, this has been solved by https://github.com/logstash-plugins/logstash-filter-kv/pull/31 and ill close it.
