### ISSUE TITLE
Add 'tag_on_failure' property

### ISSUE THREAD

**Issue by hartfordfive** [logstash-plugins/logstash-filter-kv#25]
It would be great if this filter could optionally add a custom tag upon failure, such as the grok or date filter. This would be extremely useful in a multi-tenancy environment where the Logstash instance is processing many different kv filter instances.  It would allow you to isolate which kv filter failed, and also the specific tenant.

**Comment by hartfordfive** [comment]
I've submitted a [PR](https://github.com/logstash-plugins/logstash-filter-kv/pull/26) for this feature.

**Comment by colinsurprenant** [comment]
This feature is now part of the filter. Closing.
