### ISSUE TITLE
ArgumentError: invalid byte sequence 

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-filter-kv#4]
i am getting the following error in the log then logstash fails to accept new messages 

{:timestamp=>"2014-08-26T07:58:32.480000-0700", :message=>"Exception in filterworker", "exception"=>#<ArgumentError: invalid byte sequence in UTF-8>, "backtrace"=>["org/jruby/RubyString.java:5127:in `scan'", "/opt/logstash/lib/logstash/filters/kv.rb:209:in `parse'", "/opt/logstash/lib/logstash/filters/kv.rb:175:in `filter'", "(eval):245:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}

Moved from https://logstash.jira.com/browse/LOGSTASH-2284

**Comment by ph** [comment]
I am pretty sure this is fixed with the `utf-8` replace we have in place.
We had this issue in the S3 input if the string wasn't correctly decoded before doing any string manipulation. If the user uses the UTF-8 Charset, the problematic characters will be escaped.

**Comment by stachdude** [comment]
@ph As I understand this change hasn't been commited yet as I'm having the same issue with latest version of the plugin.

```
{:timestamp=>"2015-02-17T15:48:46.486000+0100", :message=>"Exception in filterworker", "exception"=>#<ArgumentError: invalid byte sequence in UTF-8>, "backtrace"=>["org/jruby/RubyString.java:5127:
filters/kv.rb:229:in `parse'", "/opt/logstash/lib/logstash/filters/kv.rb:190:in `filter'", "(eval):154:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeli
ib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}
```

**Comment by stachdude** [comment]
ok, I think I resolved the issue, in my case anyway, by changing the line 229 of the 0.1.4 version
```
-    text.scan(@scan_re) do |key, v1, v2, v3|
+    text.force_encoding(Encoding::ISO_8859_2).encode(Encoding::UTF_8).scan(@scan_re) do |key, v1, v2, v3|
``` 
Before the change I had multiple crashes a day, now 24h without a crash so far, I know there is probably a better and cleaner way of fixing this, as I am no ruby expert, but I had to resolve the issue asap.

**Comment by ph** [comment]
The fix should be done upstream in the `input`, what input are you currently using?

**Comment by stachdude** [comment]
```udp``` and ```tcp```, but I'm pretty sure that in my case the problem was not the ```input ```, as some filters, cipher for example, returns string in a different encoding.

In my case, cipher caused a lot of errors, because of that I've created my own filter which decrypts part of the message, and returns encoded UTF-8 (cipher returns ACSII-8BIT) decrypted string. Force encoding resolved the issue with ```elasticsearch_http``` throwing ```UndefinedConversionError ASCII-8BIT to UTF-8``` and being unable to flush messages, but that started the problem with kv, which was a bit worse as it was crashing the whole logstash process.

**Comment by ph** [comment]
You could also use the `Util::Charset` class like I am doing in this urldecode filter:
https://github.com/logstash-plugins/logstash-filter-urldecode/blob/master/lib/logstash/filters/urldecode.rb#L26
https://github.com/logstash-plugins/logstash-filter-urldecode/blob/master/lib/logstash/filters/urldecode.rb#L51

This will escape the invalid utf-8 characters for you.

**Comment by stachdude** [comment]
Yup, thanks that is way much cleaner. Testing the stability now.

**Comment by talevy** [comment]
Look like this has been resolved. I'll close this issue for now
