### ISSUE TITLE
Documentation for https://github.com/logstash-plugins/logstash-filter-kv/pull/31 not showing

### ISSUE THREAD

**Issue by mut3** [logstash-plugins/logstash-filter-kv#40]
https://github.com/logstash-plugins/logstash-filter-kv/pull/31 is a wonderful feature addition to kv, but the documentation https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html does not seem to contain documentation for `transform_key` or `transform_value`

They seem to be properly documented here https://github.com/logstash-plugins/logstash-filter-kv/edit/master/lib/logstash/filters/kv.rb, which is where the docs should source from.

Perhaps this is less of a bug and more a request to rebuild the docs.

**Comment by colinsurprenant** [comment]
This is now part of the docs. Closing.
