### ISSUE TITLE
Statistical error

### ISSUE THREAD

**Issue by 81643031** [logstash-plugins/logstash-filter-kv#45]
Why the sample data and statistical data error to 5%
- Version:5.1.1
- Operating System:rhel 6.2
- Steps to Reproduce  
ELK	     DB	  ELK-DB（error?
1,644 	1643	  1	          
837	    836	    1	          
554	    554	  	0           
463	    463	  	0           
487	    487	  	0           
678	    678	  	0           
2,073	  2073	  0	          
5,983   6021	  -38	        
19,491	19387	  104	        
22,766	22600	  166	        
20,634	20562	  72	        
18,600	18484	  116	        
14,386	14631	  -245	      
15,243	15244	  -1	        
19,783	19964	  -181	      
20,082	20006	  76	        
20,737	20517	  220	        
17,906	17934	  -28	        
12,164	11928	  236	        
9,004	  8924	  80	        
8,096	  8091	  5	          
7,257	  7205	  52	        
5,490	  5489	  1	          
3,278	  3253	  25	        
                            
Total                       
247,636	 246974	662

**Comment by colinsurprenant** [comment]
I have absolutely no idea to what this issue is about. Closing. Please feel free to reopen if needed.
