### ISSUE TITLE
Not splitting on all instances of field_split_pattern

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-filter-kv#60]
- Version:  Logstash 6.2.4 w/include KV filter
- Operating System:  MacOS
- Config File
```
input {
  file {
    path => "/PATH/TO/KVTEST.txt"
    sincedb_path => "/dev/null"
    start_position => "beginning"
    ignore_older => 0
  }
}
filter {
  kv {
    field_split_pattern => "!!!!!"
  }
}
output {
  stdout {
    codec => rubydebug {}
  }
}
```
- Sample Data:
```
svc=http!!!!!req="POST /digest.html HTTP/1.1" 9!!!!!msg="Javascript pattern detected! applet matches #1 in a1"
```
- Result:
```
{
    "svc" => "http",
    "req" => "POST /digest.html HTTP/1.1\" 9!!!!!msg=\"Javascript pattern detected! applet matches #1 in a1",
}
```
- Expected:
```
{
    "svc" => "http",
    "req" => "POST /digest.html HTTP/1.1\" 9",
    "msg" => "Javascript pattern detected! applet matches #1 in a1"
}
```
The result is the same with simple single character delimiter and using `field_split`.

**Comment by yaauie** [comment]
The plugin is getting thrown off by the `" 9"` that is outside of the quotes for value of `req`; when it encounters a double-quote, it currently captures until a double-quote that is immediately followed by either a new key or end-of-input, and doesn't know how to handle a scenario where a quoted value isn't the _entire_ value.

**Comment by colinsurprenant** [comment]
@robcowart a number of improvements have been made related to this, I will close this issue, please feel free to reopen if needed.

**Comment by robcowart** [comment]
No worries. I was surprised this was still open. I should have closed it a while ago.
