### ISSUE TITLE
New issue in logstash-filter-kv-4.1.1,

### ISSUE THREAD

**Issue by LiuHarry1** [logstash-plugins/logstash-filter-kv#63]
I have below new issue which seems to be introduced by the change in logstash-filter-kv-4.1.1,
kv {
field_split => "\\|"
}
Below message is log message
type=[emc]|cause=[key is good]|flag=[P]|msg=[asdf
ffff=
ddd=]
then it will convert to below json message:
"cause": "key is good",
"msg":"[asdf"
"ffff=":"ddd=]"

Expected result is
"cause": "key is good",
"msg":"[asdf\nffff=\nddd=]"

**Comment by colinsurprenant** [comment]
Thanks for the report @LiuHarry1 
Version 4.1.2 was released since your comment - could you please rerun you test on the latest version to make sure it is still a problem?

**Comment by colinsurprenant** [comment]
Closing. Please feel free to reopen if needed.
