### ISSUE TITLE
Unconfirmed: Downgraded from 4.2.0 to 4.1.2 and everything started working again, LS 6.4

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-filter-kv#73]
From a SFDC ticket.

> We upgraded logstash from 6.3 to 6.4 and now one of my pipelines isn't working correctly. I suspect it has something to do with the logstash-filter-kv and have tried downgrading that but it still doesn't work correctly.

I asked for clarification on `isn't working correctly` but got this answer and a closed ticket.

> I downgraded logstash-filter-kv from 4.2.0 to 4.1.2 and everything started working again.

**Comment by colinsurprenant** [comment]
Performance regression were fixed in 4.2.1. I will go ahead and close this.
