### ISSUE TITLE
Regex is slow for text parsing job

### ISSUE THREAD

**Issue by dlee-libo** [logstash-plugins/logstash-filter-kv#75]
Hi guys, recently I'm working on improving our team's logstash performance. After some profiling, I find out that the kv plugin costs lots of CPU time. So I read the source code, and I realize that kv plugin is using regex to perform its job. I understand that by using regex it can easily support some advanced features such like using regex pattern as field splitter. But for very simple use case, e.g. `kv {source => 'some_source'}`, regex seems too much overhead.

Most regex engine uses backtracking or NFA rather than DFA which causes bad performance in some patterns. As for kv plugin, `'([^']+)'|\\(([^\\)]+)\\)|\\[([^\\]]+)\\]|<([^>]+)>|((?:\\\\ |[^ ])+))` cause the engine to scan the input over and over again if the input like `" name= (x " * repeat many times`. While this can be easily avoided if we parse text manually.

So I think maybe we can use some manually parsing algorithm when there is no advanced features involved. Actually I do developed an algorithm to perform same jobs as `kv {source => 'message'}`. I tested the new algorithm with our production input. To process 800K message, kv plugin used 19s, algorithm I developed used only 4s. As for input mentioned above `" name=(x " repeat 10240 times`, kv used 7934ms, while the algorithm I developed only used 12ms.

**Comment by colinsurprenant** [comment]
@dlee-libo thanks for your input!
In all the cases where parsing is needed, a custom tailored fit  parser will always be faster than a more generic parser. 
I like the idea of providing an optimized path for the simple case of `{source => "foo"}`. Please feel free to submit suggestion code or better a PR to improve. 
/cc @yaauie

**Comment by colinsurprenant** [comment]
@dlee-libo couldn't you just add your Java code in this plugins under `src/main/java/...` and add the proper Gradle tasks to handle the compilation and jar generation and simply call your Java parser class  from JRuby? 

This is our current "hybrid" plugin model (until we release our pure Java plugin model), it is not well documented but we're using it in various plugins like [geoip](https://github.com/logstash-plugins/logstash-filter-geoip), [date](https://github.com/logstash-plugins/logstash-filter-date), [useragent](https://github.com/logstash-plugins/logstash-filter-useragent), ...
