### ISSUE TITLE
Add 'coerce' property to cast decimals to integers

### ISSUE THREAD

**Issue by ivssh** [logstash-plugins/logstash-filter-kv#78]
Some logs like tor logs have time stamp with decimal in it like `"timestamp": "1547308761.076351"`. Need such a feature to cast it to integer so that Elasticsearch accepts it in a valid timestamp format.

**Comment by yaauie** [comment]
Type conversions can easily be done with [Mutate's `convert` directive](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-convert), and adding schema/conversions here would likely add a fair bit of complexity.
~~~
filter {
  if [timestamp] =~ /^[0-9]+(?:\.[0-9]+)?$/ {
    mutate {
      convert => {
        "timestamp" => "float"
      }
    }
  }
}
~~~

**Comment by colinsurprenant** [comment]
Also this is the specific purpose of the [date filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html). 

```
bin/logstash -e 'filter{date{match => ["message", "UNIX"]}} output{stdout{codec => rubydebug}}'
1547308761.076351
{
      "@version" => "1",
       "message" => "1547308761.076351",
    "@timestamp" => 2019-01-12T15:59:21.076Z,
          "host" => "mbp15r.local",
          "type" => "stdin"
}
```

Closing this, please feel free to reopen if needed.
